/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Book = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'author' : IDL.Text,
  'available' : IDL.Bool,
  'genre' : IDL.Text,
});
export const LibraryInfo = IDL.Record({
  'about' : IDL.Text,
  'hours' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBook' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addService' : IDL.Func([IDL.Text], [], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getBooksByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
  'getLibraryInfo' : IDL.Func([], [LibraryInfo], ['query']),
  'updateBook' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateLibraryInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateService' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Book = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'author' : IDL.Text,
    'available' : IDL.Bool,
    'genre' : IDL.Text,
  });
  const LibraryInfo = IDL.Record({
    'about' : IDL.Text,
    'hours' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
  });
  
  return IDL.Service({
    'addBook' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addService' : IDL.Func([IDL.Text], [], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAllServices' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getBooksByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Book)], ['query']),
    'getLibraryInfo' : IDL.Func([], [LibraryInfo], ['query']),
    'updateBook' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateLibraryInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateService' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };