/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'id' : bigint,
  'title' : string,
  'author' : string,
  'available' : boolean,
  'genre' : string,
}
export interface LibraryInfo {
  'about' : string,
  'hours' : string,
  'name' : string,
  'address' : string,
}
export interface _SERVICE {
  'addBook' : ActorMethod<[string, string, string], bigint>,
  'addService' : ActorMethod<[string], undefined>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getAllServices' : ActorMethod<[], Array<string>>,
  'getBooksByGenre' : ActorMethod<[string], Array<Book>>,
  'getLibraryInfo' : ActorMethod<[], LibraryInfo>,
  'updateBook' : ActorMethod<
    [bigint, string, string, string, boolean],
    undefined
  >,
  'updateLibraryInfo' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateService' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];